# Generated by Django 3.0 on 2021-11-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cloth_brand', models.CharField(choices=[('killer', 'killer'), ('cambridge', 'cambridge'), ('disel', 'disel')], max_length=100)),
                ('cloth_price', models.IntegerField()),
                ('cloth_image', models.ImageField(upload_to='image/')),
                ('cloth_desc', models.TextField()),
            ],
        ),
    ]
