# Generated by Django 3.0 on 2021-11-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211128_0117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Contact',
        ),
    ]
