from django.urls import path
from .import views

urlpatterns = [
    path('', views.index,name='index'),
    path('shop/',views.shop,name='shop'),
    path('product_details/',views.product_details,name='product_details'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart/',views.cart,name='cart'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('blog/',views.blog,name='blog'),
    path('blog_single/',views.blog_single,name='blog_single'),
    path('logout/',views.logout,name='logout'),
    path('seller_index/',views.seller_index,name='seller_index'),
    path('add_clothes/',views.add_clothes,name='add_clothes'),
    path('view_clothes/',views.view_clothes,name='view_clothes'),
    path('cloth_detail/<int:pk>/',views.cloth_detail,name='cloth_detail'),
    path('cloth_edit/<int:pk>/',views.cloth_edit,name='cloth_edit'),
    path('cloth_delete/<int:pk>/',views.cloth_delete,name='cloth_delete'),
    path('user_cloth_detail/<int:pk>/',views.user_cloth_detail,name='user_cloth_detail'),
    path('contact/',views.contact,name='contact'),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_from_wishlist/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('add_to_Cart/<int:pk>/',views.add_to_Cart,name='add_to_Cart'),
    path('remove_from_cart/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
    path('change_qty/',views.change_qty,name='change_qty'),
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('myorder/',views.myorder,name='myorder'),
    path('search/',views.search,name='search'),
    path('validate_email/',views.validate_email,name='validate_email'),
]
